
apiVersion: v1
kind: Pod
metadata:
  name: builder
  namespace: default
  labels:
    app: builder
spec:
  containers:
  - image: pcarlton/tekton-buildkit-builder:0.1.1
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: builder
    resources:
      limits:
        cpu: "8"
        memory: 16G
      requests:
        cpu: "4"
        memory: 8G
    securityContext:
      privileged: false
  restartPolicy: Always
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  nodeSelector:
    beta.kubernetes.io/arch: amd64
