
apiVersion: v1
kind: Pod
metadata:
  name: builder
  namespace: default
  labels:
    app: builder
spec:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - image: pcarlton/tekton-buildkit-builder:0.1.1
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: builder
  restartPolicy: Always