apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: paulcarlton-master
  region: eu-west-1
  version: "1.22"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: s3-reader
      attachPolicyARNs:
      - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"

vpc:
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
  publicAccessCIDRs: ["31.54.142.17/32", "17.0.0.0/8"]

managedNodeGroups:
  - name: ng-2-amd
    minSize: 1
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    labels: {role: amd}
    tags:
      nodegroup-role: amd
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
    instanceType: t3a.2xlarge

  - name: ng-3-arm
    minSize: 1
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    instanceType: m6g.2xlarge
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    labels: {role: arm}
    tags:
      nodegroup-role: arm
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "paulcarlton-ww"
      repository: "ww-master"
      branch: "main"
      namespace: "flux-system"
      path: "./cluster"
      private-key-file: info/cluster-keys/ww-master/cluster-keys

secretsEncryption:
  keyARN: arn:aws:kms:eu-west-1:482649550366:key/12a962b2-f279-4eaf-bf09-36d97e651ee7