apiVersion: v1
kind: Pod
metadata:
  name: kraan-build-build-pod1
  namespace: tekton-builder
spec:
  activeDeadlineSeconds: 5355
  containers:
  - args:
    - buildctl
    - --
    - --debug
    - --addr=buildkit:tcp://buildkitd:1234
    - --tlscacert
    - /certs/ca.pem
    - --tlscert
    - /certs/cert.pem
    - --tlskey
    - /certs/key.pem
    - build
    - --progress=plain
    - --frontend=dockerfile.v0
    - --opt
    - filename=./Dockerfile
    - --local
    - context=.
    - --local
    - dockerfile=.
    - --output
    - type=image,name=pcarlton/kraan:3.0.0-dev,push=true
    - --export-cache
    - type=inline
    - --import-cache
    - type=registry,ref=pcarlton/kraan:3.0.0-dev
    command:
    - /tekton/bin/entrypoint
    image: moby/buildkit:master-rootless
    imagePullPolicy: IfNotPresent
    name: step-build-and-push
    resources: {}
    terminationMessagePath: /tekton/termination
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /certs
      name: certs
      readOnly: true
    workingDir: /workspace/source
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: certs
    secret:
      defaultMode: 420
      secretName: buildkit-client-certs
