---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-image
  namespace: tekton-builder
spec:
  description: |
    clone repo and build image
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: branch-name
    type: string
    description: The git branch to clone.
  - name: dockerfile
    type: string
  - name: builder-image
    type: string
  - name: buildkit-daemon
    type: string
  - name: client-certs
    type: string
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the image to be built.
  - name: registry-creds
    description: |
      This workspace will be mapped to a secret containing registry credentials.
  resources:
  - name: image
    type: image
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.branch-name)
  - name: build
    runAfter: ["fetch-repo"]
    taskRef:
      name: buildkit
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: shared-data
    resources:
      outputs:
      - name: image
        resource: image
    params:
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: BUILDKIT_CLIENT_IMAGE
      value: $(params.builder-image)
    - name: BUILDKIT_DAEMON_ADDRESS
      value: $(params.buildkit-daemon)
    - name: BUILDKIT_CLIENT_CERTS
      value: $(params.client-certs)
