---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: kraan-build
  namespace: tekton-builder
spec:
  podTemplate:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: "tekton.dev/pipelineRun"
              operator: In
              values:
              - clone-build
          topologyKey: kubernetes.io/hostname
  pipelineRef:
    name: build-image
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  resources:
    - name: image
      resourceSpec:
        type: image
        params:
          - name: url
            value: pcarlton/kraan:3.0.0-dev
  params:
  - name: repo-url
    value: https://github.com/paulcarlton-ww/kraan.git
  - name: branch-name
    value: master
  - name: builder-image
    value: moby/buildkit:master-rootless
  - name: buildkit-daemon
    value: buildkit:tcp://buildkitd:1234
  - name: client-certs
    value: buildkit:buildkit-client-certs
  - name: dockerfile
    value: ./Dockerfile
