apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    buildx.docker.com/platform: linux/amd64
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-06-16T16:21:17Z"
  generation: 1
  labels:
    app: amd64builder
  name: amd64builder
  namespace: builder
  resourceVersion: "12075383"
  uid: 03996b61-cd19-4e61-b449-cab53c9a83f4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: amd64builder
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        buildx.docker.com/platform: linux/amd64
      labels:
        app: amd64builder
    spec:
      containers:
      - image: moby/buildkit:v0.10.3
        imagePullPolicy: IfNotPresent
        name: buildkitd
        readinessProbe:
          exec:
            command:
            - buildctl
            - debug
            - workers
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "8"
            memory: 16G
          requests:
            cpu: "4"
            memory: 8G
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    buildx.docker.com/platform: linux/arm64
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-06-16T16:21:17Z"
  generation: 1
  labels:
    app: arm64builder
  name: arm64builder
  namespace: builder
  resourceVersion: "12075390"
  uid: b4632e9d-3ea0-4d4f-be9e-c2fb957e4ef8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: arm64builder
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        buildx.docker.com/platform: linux/arm64
      creationTimestamp: null
      labels:
        app: arm64builder
    spec:
      containers:
      - image: moby/buildkit:buildx-stable-1-rootless
        imagePullPolicy: IfNotPresent
        name: buildkitd
        readinessProbe:
          exec:
            command:
            - buildctl
            - debug
            - workers
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "8"
            memory: 16G
          requests:
            cpu: "4"
            memory: 8G
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/arch: arm64
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
